# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0429d2573a7b36073916f532449983bbdaaf943c4e707b3d98213847a11e56bce6521cff25b68033da5d47ddb25a734a841b90e4293800e29c7e78f65bf01d14

test:
  secret_key_base: d31087f04da83db5d59b427e490177b47b05e766dd274e7fcfd0b8b84888d487f38ad0e1df29d3b4b6be65e1f3fee352a008971c0db39fdc3c9c00f4b4b46970

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
